
[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'

[character]
success_symbol = '[âŒ¨ï¸](bold green)'
error_symbol = '[îª‡ ](bold red)'

[cmake]
style = 'bold 22'

[cmd_duration]
show_milliseconds=true

[conda]
symbol = 'ó±” '

[container]
style = 'bold 33 dimmed'

[directory]
truncation_symbol = 'ó°‡˜/'
home_symbol = 'î¬† '

[env_var.USER]
default = 'unknown'
symbol = 'ï• '
format = 'as [$env_value]($style) '
style = 'italic 75'

[gradle]
symbol = 'ó°Ÿ† '
style = 'bold 43'

[hostname]
ssh_only = false
style = 'bold dimmed 42'

[jobs]
number_threshold = 1
symbol = 'ï‚® '

[kotlin]
symbol = 'î˜´ '

[lua]
symbol = 'ó°¢± '

[memory_usage]
disabled = false
symbol = 'ó°› '
style = 'bold dimmed 215'
format = '$symbol [${ram} \($ram_pct\)( | ${swap})]($style) '

[os]
disabled = false

# This is the default symbols table.
[os.symbols]
Alpine = "ïŒ€  "
Amazon = "ï‰°  "
Android = "ó°€²  "
Arch = "ó°£‡  "
CentOS = "ó±„š  "
Debian = "î¯…  "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ïŒ¢  "
Fedora = "ó±„›  "
FreeBSD = "ïŒŒ  "
Garuda = "ğŸ¦… "
Gentoo = "ïŒ  "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ïŒ¦  "
Linux = "ïŒš  "
Macos = "îœ‘  "
Manjaro = "ó±˜Š  "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ïŒ  "
NetBSD = "ğŸš© "
NixOS = "ïŒ“  "
OpenBSD = "ïŒ¨  "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ïŒ”  "
OracleLinux = "ğŸ¦´ "
Pop = "ïŒª  "
Raspbian = "îœ¢  "
Redhat = "ó±„›  "
RedHatEnterprise = "ïŒ–  "
Redox = "ğŸ§ª "
Solus = "ïŒ­  "
SUSE = "ïŒ”  "
Ubuntu = "î¯‰  "
Unknown = "î¯ƒ  "
Windows = "î˜ª  "

[php]
symbol = 'îœ½ '

[python]
symbol = 'îˆµ '
style = 'bold 220'

[scala]
symbol = 'îœ· '

[shlvl]
disabled = false
threshold = 1
symbol = 'ó°•‡ '

[sudo]
disabled = false
symbol = 'î¬‘ '
format = '[$symbol]($style) '
style = 'bold 222'


